---
name: Prettier

on:
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install npm Modules
        uses: ./.github/actions/install-modules

      - name: Run Prettier
        run: npm run format
